In [ ]:
def calculate_change(payment, cost):
    money = payment - cost
    unit = [50000,10000,5000,1000]
    for i in range(len(unit)):
        print('{}원 지페 : {}장'.format(unit[i],money//unit[i]))
        money = money % unit[i]
calculate_change(100000, 33000) # 함수 호출
print('=================')
calculate_change(500000, 378000)

50000원 지페 : 1장
10000원 지페 : 1장
5000원 지페 : 1장
1000원 지페 : 2장
=================
50000원 지페 : 2장
10000원 지페 : 2장
5000원 지페 : 0장
1000원 지페 : 2장

In [ ]:
def abs(num):
    # return만나면 함수가 종료됨
    if num > 0:
        result =  num
    else:
        result =  num * -1
    return result
print(abs(-7))
print(abs(12))

7
12

In [ ]:
# 두수를 받아서 사칙연산결과를 출력
def cal(num1, num2):
    print("{} + {} = {}".format(num1,num2,num1+num2))
    print("{} - {} = {}".format(num1, num2, num1 - num2))
    print("{} * {} = {}".format(num1, num2, num1 * num2))
    print("{} / {} = {}".format(num1,num2,num1/num2))

cal(12, 3)

12 + 3 = 15
12 - 3 = 9
12 * 3 = 36
12 / 3 = 4.0

In [ ]:
x = 20; y = 10
k = [1,2,3]
# call함수에서 x,y를 받아서 x+=y를 실행한후에
# 함수 안에서 x, y출력, 함수 밖에서 x,y출력하고 비교
# k에 4를 추가하고 함수 안과 밖에서 출력
def call(x, y, k):
    x += y
    k.append(4)
    print('x =',x,', y =',y)
    print(k)
call(x,y,k)
print('x =',x,', y =',y)
print(k)

x = 30 , y = 10
[1, 2, 3, 4]
x = 20 , y = 10
[1, 2, 3, 4]

In [ ]:
def call(x):
    x[0] = 10
    print(x)
x = [1,2,3,4,5]
# list, 배열, 객체는 주소를 전달
call(x)
print(x)

[10, 2, 3, 4, 5]
[10, 2, 3, 4, 5]

In [ ]:
def hello():
    print('안녕 컴동지 !')
    print('대박 ~')
# 함수 호출
hello()
hello()

안녕 컴동지 !
대박 ~
안녕 컴동지 !
대박 ~

In [ ]:
# *는 복수의 데이터를 가진 변수
a, *b = [1,2,3,4,5]
print(a)
print(b)
*a,b = [1,2,3,4,5]
print(a)
print(b)
a,*b,c = [1,2,3,4,5]
print(a)
print(b)
print(c)
# a,*b,*c = [1,2,3,4,5] b와 c에 몇개씩인지 구별못함

1
[2, 3, 4, 5]
[1, 2, 3, 4]
5
1
[2, 3, 4]
5

In [ ]:
def call(name):
    print('안녕 !', name)
    print('으이그 ~')
def plus(a, b):
    print('안녕 ',a)
    print('대박', b)
    print(a + b)
# 함수를 호출할 경우에는 name에 들어갈 값 전달
call('김태희')
call(11)
plus(12, 5)

안녕 ! 김태희
으이그 ~
안녕 ! 11
으이그 ~
안녕  12
대박 5
17

In [ ]:
def f1(x):
    # 지역변수
    # 함수실행함 때 메모리에 생성
    # 함수가 끝나면 없어짐
    x = 7
    print('x =',x)
# 전역변수
x = 2
f1(x)
print('x =',x)

x = 7
x = 2

In [ ]:
def f1(a):
    global x # x가 전역변수
    x = a
    x = 7
    print('x =',x)
# 전역변수
x = 2
f1(x)
print('x =',x)

x = 7
x = 7

In [ ]:
def fa(a, *k):
    print(a)
    print(k)
fa(2,5,6,7,9)

2
(5, 6, 7, 9)

In [ ]:
# 초기값을 정해놓고 해당하는 매개변수 값이 없으면 초기값 사용
# 이렇게 사용하는 것을 optional parameter
def intro(name, age, hobby='졸기'):
    print('이름 :',name)
    print('나이 :',age)
    print('취미 :',hobby)
intro('철수',25,'웃기')
intro('보미',21)

이름 : 철수
나이 : 25
취미 : 웃기
이름 : 보미
나이 : 21
취미 : 졸기

In [ ]:
def person(height, weight):
    #                    height는 정수
    print('키 : ', format(height,'d'))
    print('몸무게 :',weight)
person(174, 70)
person(weight=67,height=181)

키 :  174
몸무게 : 70
키 :  181
몸무게 : 67

In [ ]:
# *변수 : 값이 여러개
# **변수 : '키=값'형태가 여러개
def f(height, weight,**k):
    print('키 :',height)
    print('몸무게 :',weight)
    print(k)
f(height=182,weight=89, age=27, name='강다니엘')

키 : 182
몸무게 : 89
{'age': 27, 'name': '강다니엘'}

In [ ]:
def sum(a, b):
    return a + b
def print_sum(a, b):
    print(a + b)
sum(2, 4)  # 이자리에 6이 들어 가지만 출력은 하지 않음
print(sum(2, 4))  # 6을 출력
print_sum(2, 4)  # 6을 출력
print(print_sum(2, 4)) # 6을 출력하고 None을 출력
# return이 없을 경우는 받는 값이 없으므로 None

6
6
6
None

In [ ]:
def calculate_seven():
    return int("5") + int(2.0) # 5+2 = 7
    print("럭키 7을출력합니다.") # 실행 안됨

num = calculate_seven()
print(num)

7

In [ ]:
def multiply_by_two():
    global x
    x = x * 2
def multiply_by_three():
    y = 2  # local
    y = y * 3
x = 2
multiply_by_two()
# x는 global이므로 변경된 4가 출력
print(x)
y = 2
multiply_by_three()
# y는 지역함수에서 변경이 내용이 반영되지 않으므로 2
print(y)

4
2

In [ ]:
def plus(num1, num2):
    # return 호출한 곳으로 값을 전달
    return num1 + num2
print(plus(12, 4))
result = plus(3, 6)
print(result)

16
9

In [ ]:
def cal(num1, num2):
    print('%d + %d = %d' % (num1,num2,num1+num2))
    return
    # return에서 함수가 종료됐으므로 하단 문장 실행 안함
    print('%d - %d = %d' % (num1, num2, num1 - num2))
cal(12,3)

12 + 3 = 15

In [ ]:
def ret(a, b):
    # python에서는 return 값이 복수가 가능
    return b, a
    # return을 만나면 거기까지 함수 끝
    print("대박")
print(ret(12, 67))

(67, 12)

In [ ]:
x = 0
def f1():
#   global x
    x = 7
    print('x =',x)
f1()
print('x =',x)
def f2(a, *k):
    print(a)
    print(k)
f2(2,5,8,3,5) # 2와 나머지 데이터 출력 하는 함수 작성
def f3(name,age, **k):
    print(name)
    print(age)
    print(k)
f3(name='보미',age=21,hobby='지각하기',food='빵')
# 이름, 나이, 나머지 출력하는 함수 작성

x = 7
x = 0
2
(5, 8, 3, 5)
보미
21
{'hobby': '지각하기', 'food': '빵'}

In [ ]:
def is_evenly_divisible(number):
    # 짝수면 True, 홀수면 False
    return number % 2 == 0

print(is_evenly_divisible(3))
print(is_evenly_divisible(7))
print(is_evenly_divisible(8))

False
False
True

In [ ]:
def is_odd(num):
    if num % 2 == 0:
        result = "짝수"
    else:
        result = "홀수"
    return result
print(is_odd(3))
print(is_odd(7))
print(is_odd(8))

홀수
홀수
짝수

In [ ]:
# 입력으로 들어오는 모든 수의 평균 값을 계산해 주는 함수를 작성
# 단 입력으로 들어오는 수의 개수는 정해져 있지 않다.
# ※ 평균 값을 구할 때 len 함수를 사용해 보자
def average(*val):
    sum = 0
    for i in val:
        sum += i
    print("합계 : {0:d}, 평균 : {1:.2f}".
          format(sum, sum/len(val)))
average(45, 67, 88)
average(78, 99, 88, 66)

합계 : 200, 평균 : 66.67
합계 : 331, 평균 : 82.75